JOY_PROMPTS = [
    "She laughed with delight when she saw the surprise party.",
    "He felt a wave of happiness wash over him as he held his newborn daughter.",
    "The children squealed with joy as they ran through the sprinklers.",
    "She couldn't stop smiling after he proposed.",
    "Tears of happiness streamed down her face as she opened the letter.",
    "He grinned from ear to ear when the team announced his promotion.",
    "The reunion filled her heart with warmth she hadn't felt in years.",
    "She danced around the kitchen, unable to contain her excitement.",
    "His laughter echoed through the house as he played with the puppy.",
    "She felt pure bliss watching the sunrise from the mountaintop.",
    "He whooped with delight when his name was called as the winner.",
    "Her face lit up the moment she recognized her old friend.",
    "They hugged and cried, overjoyed to be together again.",
    "He felt a deep contentment settle over him as he watched her sleep.",
    "She beamed with pride as her daughter crossed the finish line.",
    "The crowd erupted in cheers when the goal was scored.",
    "He felt elated reading the acceptance letter from the university.",
    "She giggled uncontrollably as he told the story for the third time.",
    "His heart soared when he saw her waiting at the airport.",
    "She felt blessed and joyful surrounded by everyone she loved.",
]