NEUTRAL_PROMPTS = [
    "She walked to the store to buy some groceries.",
    "The report was submitted before the end of the day.",
    "He read the instructions carefully before assembling the shelf.",
    "The meeting was scheduled for Tuesday afternoon.",
    "She typed the last paragraph and saved the document.",
    "The train arrived two minutes ahead of schedule.",
    "He ordered the usual coffee and sat by the window.",
    "The package was delivered to the front door.",
    "She finished the crossword puzzle before breakfast.",
    "The temperature was mild for that time of year.",
    "He updated the spreadsheet with the latest figures.",
    "The library closed at nine on weekday evenings.",
    "She replied to the email within the hour.",
    "The garden needed watering after three dry days.",
    "He parked the car and walked to the entrance.",
    "The invoice was processed and sent to accounting.",
    "She chose the window seat on the commuter train.",
    "The agenda was circulated before the meeting started.",
    "He noted the page number and closed the book.",
    "The system update completed without any errors.",
]